const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "94763007898"
const SESSION_ID = "PRABATH-MD~9UQkyJCJ#HMlHkmqrg-T_9TdUWP515DKTMxsQcSXBu0JmW_OQSQE"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
